# Generated by Django 4.2.20 on 2025-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_watchlist_watchliststock_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchliststock',
            name='symbol',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchliststock',
            unique_together={('watchlist', 'symbol')},
        ),
    ]
