# Generated by Django 4.2.20 on 2025-03-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_useraccount_portfolio_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_side',
            field=models.CharField(default='Buy', max_length=32),
        ),
    ]
