# Generated by Django 4.2.20 on 2025-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_orderhistory_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order_side',
            field=models.CharField(default='BUY', max_length=32),
        ),
    ]
