# Generated by Django 4.2.20 on 2025-03-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_orderhistory_order_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(default='MARKET', max_length=3),
        ),
    ]
