# Generated by Django 4.2.20 on 2025-03-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_orderhistory_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=100000),
        ),
    ]
