# Generated by Django 4.2.20 on 2025-03-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_useraccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profit_loss_percent',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='value',
        ),
    ]
