# Generated by Django 4.2.20 on 2025-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_portfolio_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
