# Generated by Django 4.2.20 on 2025-03-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_pricealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='direction',
            field=models.BooleanField(default=True),
        ),
    ]
